config/routes.rb
Creamery2012::Application.routes.draw do

  # Generated model routes
  resources :stores
  resources :employees
  resources :assignments
  resources :shifts
  resources :jobs
  resources :users
  resources :sessions

  # Authentication routes
  match 'user/edit' => 'users#edit', :as => :edit_current_user
  match 'signup' => 'users#new', :as => :signup
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login
  
  # Semi-static page routes
  match 'home' => 'home#index', :as => :home
  match 'about' => 'home#about', :as => :about
  match 'contact' => 'home#contact', :as => :contact
  match 'privacy' => 'home#privacy', :as => :privacy
  match 'search' => 'home#search', :as => :search
  
  # Set the root url
  root :to => 'home#index'
  
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  # Callbacks
  before_save :reformat_phone
  before_validation :reformat_ssn

  mount_uploader :photo, PhotoUploader  
  
  # Relationships
  has_many :assignments
  has_many :stores, :through => :assignments
  has_many :shifts, :through => :assignments
  has_one :user

  accepts_nested_attributes_for :assignments, :reject_if => lambda{|assignment| assignment[:employee_id].blank?}
  
  # Validations
  validates_presence_of :first_name, :last_name
  validates_date :date_of_birth, :on_or_before => lambda { 14.years.ago }, :on_or_before_message => "must be at least 14 years old"
  validates_format_of :phone, :with => /^\(?\d{3}\)?[-. ]?\d{3}[-.]?\d{4}$/, :message => "should be 10 digits (area code needed) and delimited with dashes only", :allow_blank => true
  validates_format_of :ssn, :with => /^\d{3}[- ]?\d{2}[- ]?\d{4}$/, :message => "should be 9 digits and delimited with dashes only"
  validates_inclusion_of :role, :in => %w[admin manager employee], :message => "is not an option"
  validates_uniqueness_of :ssn
  
  # Scopes
  scope :younger_than_18, where('date_of_birth > ?', 18.years.ago.to_date)
  scope :is_18_or_older, where('date_of_birth <= ?', 18.years.ago.to_date)
  scope :active, where('active = ?', true)
  scope :inactive, where('active = ?', false)
  scope :regulars, where('role = ?', 'employee')
  scope :managers, where('role = ?', 'manager')
  scope :admins, where('role = ?', 'admin')
  scope :alphabetical, order('last_name, first_name')
  
  # Other methods
  def recent_hours
    hours = 0
    self.current_assignment.shifts.completed.for_past_days(14).each do |x|
      if x.start_time < x.end_time
        hours += (x.end_time.to_s(:number).to_i - x.start_time.to_s(:number).to_i)/(60*60)
      else
        hours += (24*60*60 - x.start_time.to_s(:number).to_i)/(60*60)
        hours += (x.end_time.to_s(:number).to_i + 24*60*60)/(60*60)
      end
    end
    return hours
  end

  def name
    "#{last_name}, #{first_name}"
  end
  
  def proper_name
    "#{first_name} #{last_name}"
  end
  
  def current_assignment
    curr_assignment = self.assignments.select{|a| a.end_date.nil?}
    # alternative method for finding current assignment is to use scope 'current' in assignments:
    # curr_assignment = self.assignments.current    # will also return an array of current assignments
    return nil if curr_assignment.empty?
    curr_assignment.first   # return as a single object, not an array
  end
  
  def over_18?
    date_of_birth < 18.years.ago.to_date
  end
  
  def age
    (Time.now.to_s(:number).to_i - date_of_birth.to_time.to_s(:number).to_i)/10e9.to_i
  end
  
  # Misc Constants
  ROLES_LIST = [['Employee', 'employee'],['Manager', 'manager'],['Administrator', 'admin']]
  
  
  # Callback code  (NOT DRY!!!)
  # -----------------------------
   private
   def reformat_phone
     phone = self.phone.to_s  # change to string in case input as all numbers 
     phone.gsub!(/[^0-9]/,"") # strip all non-digits
     self.phone = phone       # reset self.phone to new string
   end
   def reformat_ssn
     ssn = self.ssn.to_s      # change to string in case input as all numbers 
     ssn.gsub!(/[^0-9]/,"")   # strip all non-digits
     self.ssn = ssn           # reset self.ssn to new string
   end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_filter :check_login
  authorize_resource

  def index
    @employees = Employee.active.alphabetical.paginate(:page => params[:page]).per_page(10)
    @inactive_employees = Employee.inactive.alphabetical.paginate(:page => params[:page]).per_page(10)
  end

  def show
    @employee = Employee.find(params[:id])
    authorize! :read, @employee
    # get the assignment history for this employee
    @assignments = @employee.assignments.chronological.paginate(:page => params[:page]).per_page(5)
    # get upcoming shifts for this employee (later)
    
  end

  def new
    @employee = Employee.new
    authorize! :new, @employee
  end

  def edit
    @employee = Employee.find(params[:id])
    authorize! :edit, @employee
  end

  def create
    @employee = Employee.new(params[:employee])
    authorize! :create, @employee
    @employee.assignments.build
    if @employee.save
      # if saved to database
      flash[:notice] = "Successfully created #{@employee.proper_name}."
      redirect_to @employee # go to show employee page
    else
      # return to the 'new' form
      render :action => 'new'
    end
  end

  def update
    @employee = Employee.find(params[:id])
    authorize! :update, @employee
    if @employee.update_attributes(params[:employee])
      flash[:notice] = "Successfully updated #{@employee.proper_name}."
      redirect_to @employee
    else
      render :action => 'edit'
    end
  end

  def destroy
    @employee = Employee.find(params[:id])
    authorize! :destroy, @employee
    @employee.destroy
    flash[:notice] = "Successfully removed #{@employee.proper_name} from the AMC system."
    redirect_to employees_url
  end
end

app/views/employees/_assignment_history.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Store</th>
			<th>Dates</th>
			<th class="centered">Pay</th>
    </tr>
  </thead>
  <tbody>
    <% @assignments.each do |assignment| %>
      <tr>
        <td><%= link_to assignment.store.name, store_path(assignment.store) %></td>
				<td>
					<%= assignment.start_date.strftime("%m/%d/%y") %>
					<% if assignment.end_date.nil? %>
						&nbsp;&nbsp;&nbsp;<%= link_to(raw("<i class='icon-remove'></i> End"), edit_assignment_path(assignment), :class => 'btn btn-mini') %>
					<% else %>
						&nbsp;-&nbsp;<%= assignment.end_date.strftime("%m/%d/%y") %>
					<% end %>
				</td>
				<td class="centered"><%= assignment.pay_level %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @assignments, :previous_label => "Previous&nbsp;", :next_label => "&nbsp;Next" %>

app/views/employees/_current_employees.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
			<th>Phone</th>
			<th>Currently Assigned</th>
			<th>Role</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= link_to employee.name, employee_path(employee) %></td>
				<td><%= number_to_phone employee.phone unless employee.phone.nil?  %></td>
				<td><%= link_to employee.current_assignment.store.name, store_path(employee.current_assignment.store) unless employee.current_assignment.nil? %></td>
        <td><%= employee.role.capitalize %></td>
				<td>
					<%= link_to raw("<i class='icon-file'></i> Details"), employee_path(employee), :class => 'btn btn-mini' %>
          <%#= link_to raw("<i class='icon-pencil'></i> Edit"), edit_employee_path(employee), :class => 'btn btn-mini' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @employees, :previous_label => "Previous&nbsp;", :next_label => "&nbsp;Next" %>

app/views/employees/_employee_details.html.erb
<p>
	<h4>
	  Name: <%= @employee.name %>
	</h4>
</p>

<p>
  <b>SSN:</b> <%= @employee.ssn %>
</p>

<p>
  <b>Date of Birth:</b> <%= @employee.date_of_birth.strftime("%m/%d/%y") %>
</p>

<p>
  <b>Phone:</b> <%= number_to_phone @employee.phone unless @employee.phone.nil? %>
</p>

<p>
  <b>Role:</b> <%= @employee.role.capitalize %>
</p>

<p>
  <b>Pay Level:</b> <%= @employee.assignments.find(:last, :conditions => { :employee_id => @employee.id}).pay_level unless @employee.assignments.find(:last, :conditions => { :employee_id => @employee.id}).nil? %>
</p>

<p>
  <b>Active:</b> <%= @employee.active ? "Yes" : "No" %>
</p>

app/views/employees/_form.html.erb
<%= simple_form_for @employee, :html => { :class => 'form-horizontal', :multipart => true } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Employee</legend>
		
		<%= f.input :first_name %>
		<%= f.input :last_name %>
		<%= f.input :ssn, :label => "SSN" %>
		<%= f.input :date_of_birth, :label => "Date of Birth", :as => :date, :start_year => Date.today.year - 13, :end_year => Date.today.year - 75, :order => [:month, :day, :year], :include_blank => true %>
		<%= f.input :phone %>
		<%= f.input :role, :collection => Employee::ROLES_LIST %>
		<%= f.input :active %>

	<div class="field">
      <%= f.label :photo %><br />
      <%= f.file_field :photo %><br />
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', employees_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/employees/_inactive_employees.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% @inactive_employees.each do |employee| %>
      <tr>
        <td><%= link_to employee.name, employee_path(employee) %></td>
				<td>
					<%# link_to raw("<i class='icon-file'></i> Details"), employee_path(employee), :class => 'btn btn-mini' %>
          <%= link_to raw("<i class='icon-pencil'></i> Edit"), edit_employee_path(employee), :class => 'btn btn-mini' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @inactive_employees, :previous_label => "Previous&nbsp;", :next_label => "&nbsp;Next" %>

app/views/employees/_star_employees.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
			<th>Currently Assigned</th>
			<th>Hours Worked</th>
    </tr>
  </thead>
  <tbody>
    <% @employees.alphabetical.sort_by{|a| a.recent_hours}.each do |employee| %>
      <tr>
        <td><%= link_to employee.name, employee_path(employee) %></td>
				<td><%= link_to employee.current_assignment.store.name, store_path(employee.current_assignment.store) unless employee.current_assignment.nil? %></td>
        <td><%= employee.recent_hours %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @employees, :previous_label => "Previous&nbsp;", :next_label => "&nbsp;Next" %>

app/views/employees/edit.html.erb
<%= render :partial => 'form' %>

app/views/employees/index.html.erb
<div class="row">
	<div class="span8">
		<h2>Current Employees</h2>
		<%= render :partial => "current_employees" unless @employees.empty? %>
	</div>
	<div class="span4">
		<h2>Former Employees</h2>
		<%= render :partial => "inactive_employees" unless @inactive_employees.empty? %>
		
	</div>
</div>

<%= link_to raw("<i class='icon-plus icon-white'></i> Add a New Employee"), new_employee_path, :class => 'btn btn-primary', :id => 'Create Employee' %>

app/views/employees/new.html.erb
<%= render :partial => 'form' %>

app/views/employees/show.html.erb
<%# unless @employee.photo_url.nil? %>
	<p><%= image_tag @employee.photo_url %></p>
<%# end %>

<div class="row">
	<div class="span8">
		<h3><%= @employee.proper_name %>'s Details: </h3>
		<%= render :partial => "employee_details" %>
	</div>
	<div class="span4">
		<h3>Assignment History:</h3>
		<%= render :partial => "assignment_history" unless @assignments.empty? %>
		<%= link_to(raw("<i class='icon-plus icon-white'></i> New Assignment"), new_assignment_path(:id => @employee.id, :from => 'employee'), :class => 'btn btn-primary') %>
	</div>
</div>

<div class="form-actions">
  <%= link_to raw("<i class='icon-th-list'></i> Display All Employees"), employees_path, :class => 'btn'  %>&nbsp;&nbsp;
  <%= link_to raw("<i class='icon-pencil'></i> Edit #{@employee.proper_name}"), edit_employee_path(@employee), :class => 'btn' %>&nbsp;&nbsp;
  <%= link_to raw("<i class='icon-trash icon-white'></i> Delete #{@employee.proper_name}"), employee_path(@employee), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>