config/routes.rb
Creamery2012::Application.routes.draw do

  # Generated model routes
  resources :stores
  resources :employees
  resources :assignments
  resources :shifts
  resources :jobs
  resources :users
  resources :sessions

  # Authentication routes
  match 'user/edit' => 'users#edit', :as => :edit_current_user
  match 'signup' => 'users#new', :as => :signup
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login
  
  # Semi-static page routes
  match 'home' => 'home#index', :as => :home
  match 'about' => 'home#about', :as => :about
  match 'contact' => 'home#contact', :as => :contact
  match 'privacy' => 'home#privacy', :as => :privacy
  match 'search' => 'home#search', :as => :search
  
  # Set the root url
  root :to => 'home#index'
  
end

app/models/store.rb
class Store < ActiveRecord::Base
  # Callbacks
  before_save :reformat_phone
  
  # Relationships
  has_many :assignments
  has_many :employees, :through => :assignments
  has_many :shifts, :through => :assignments
  
  
  # Validations
  # make sure required fields are present
  validates_presence_of :name, :street, :city
  # if state is given, must be one of the choices given (no hacking this field)
  validates_inclusion_of :state, :in => %w[PA OH WV], :message => "is not an option"
  # if zip included, it must be 5 digits only
  validates_format_of :zip, :with => /^\d{5}$/, :message => "should be five digits long"
  # phone can have dashes, spaces, dots and parens, but must be 10 digits
  validates_format_of :phone, :with => /^\(?\d{3}\)?[-. ]?\d{3}[-.]?\d{4}$/, :message => "should be 10 digits (area code needed) and delimited with dashes only"
  # make sure stores have unique names
  validates_uniqueness_of :name
  
  # Scopes
  scope :alphabetical, order('name')
  scope :active, where('active = ?', true)
  scope :inactive, where('active = ?', false)
  
  
  # Misc Constants
  STATES_LIST = [['Ohio', 'OH'],['Pennsylvania', 'PA'],['West Virginia', 'WV']]
  
  def recent_hours
    hours = 0
    shifts.completed.for_past_days(14).each do |x|
      if x.start_time < x.end_time
        hours += (x.end_time.to_s(:number).to_i - x.start_time.to_s(:number).to_i)/(60*60)
      else
        hours += (24*60*60 - x.start_time.to_s(:number).to_i)/(60*60)
        hours += (x.end_time.to_s(:number).to_i + 24*60*60)/(60*60)
      end
    end
    return hours
  end

  def create_map_link(zoom=13,width=800,height=800)
    markers = ""; i=1
    stores.all.each do |attr|
      markers += "&markers=color:red%7Ccolor:red%7Clabel:#{i}%7C#{attr.lat},#{attr.lon}"
      i += 1
    end
    map = "http://maps.google.com/maps/api/staticmap?center=#{lat},#{lon}&zoom=13&size=#{width}x#{height}&maptype=roadmap#{markers}&sensor=false"
  end

  def single_store_map(zoom=16,width=400,height=400)
    markers = ""; i=""
    lat = self.get_lat
    lon = self.get_lon
    markers += "&markers=color:red%7Ccolor:red%7Clabel:#{i}%7C#{lat},#{lon}"
    map = "http://maps.google.com/maps/api/staticmap?center=#{lat},#{lon}&zoom=#{zoom}&size=#{width}x#{height}&maptype=roadmap#{markers}&sensor=false"
  end

  def get_lat
    return find_store_lat
  end


  def get_lon
    return find_store_lon
  end

  # Callback code
  # -----------------------------
  private
  # We need to strip non-digits before saving to db
  def reformat_phone
    phone = self.phone.to_s  # change to string in case input as all numbers 
    phone.gsub!(/[^0-9]/,"") # strip all non-digits
    self.phone = phone       # reset self.phone to new string
  end

  def find_store_lat
    coord = Geokit::Geocoders::GoogleGeocoder.geocode("#{street}, #{city}, #{state}")
    if coord.success
      return coord.lat
    else
      errors.add_to_base("Error with geocoding")
    end
  end

  def find_store_lon
    coord = Geokit::Geocoders::GoogleGeocoder.geocode("#{street}, #{city}, #{state}")
    if coord.success
      return coord.lng
    else
      errors.add_to_base("Error with geocoding")
    end
  end

end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_filter :check_login, :except => [:show]
  authorize_resource

  def index
    @stores = Store.active.alphabetical.paginate(:page => params[:page]).per_page(10)
    @inactive_stores = Store.inactive.alphabetical.paginate(:page => params[:page]).per_page(10)
  end

  def show
    @store = Store.find(params[:id])
    # get all the current assignments for this store
    @current_assignments = @store.assignments.current.by_employee.paginate(:page => params[:page]).per_page(8)
  end

  def new
    @store = Store.new
    authorize! :new, @store
  end

  def edit
    @store = Store.find(params[:id])
    authorize! :edit, @store
  end

  def create
    @store = Store.new(params[:store])
    authorize! :create, @store
    if @store.save
      # if saved to database
      flash[:notice] = "Successfully created #{@store.name}."
      redirect_to @store # go to show store page
    else
      # return to the 'new' form
      render :action => 'new'
    end
  end

  def update
    @store = Store.find(params[:id])
    authorize! :update, @store
    if @store.update_attributes(params[:store])
      flash[:notice] = "Successfully updated #{@store.name}."
      redirect_to @store
    else
      render :action => 'edit'
    end
  end

  def destroy
    @store = Store.find(params[:id])
    authorize! :destroy, @store
    @store.destroy
    flash[:notice] = "Successfully removed #{@store.name} from the AMC system."
    redirect_to stores_url
  end
end

app/views/stores/_admin_employees.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Hours Worked</th>
			<th>Last Worked</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% @admin_current_assignments.by_employee.each do |assignment| %>
      <tr>
        <td><%= link_to assignment.employee.name, employee_path(assignment.employee) %></td>
        <td><%= assignment.recent_hours %></td>
        <td><%= assignment.shifts.last.date.strftime("%m/%d/%y") unless assignment.shifts.last.nil? %></td>
        <td><%= link_to raw("<i class='icon-plus icon-white'></i> New Shift"), new_shift_path, :class => 'btn btn-primary', :id => 'Create Shift' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @admin_current_assignments, :previous_label => "Previous&nbsp;", :next_label => "&nbsp;Next" %>


app/views/stores/_admin_stores.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th class="centered">Staff Count</th>
      <th class="centered">Total Hours</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%= link_to store.name, store_path(store) %></td>
				<td class="centered"><%= store.assignments.current.size %></td>
        <td class="centered"><%= store.recent_hours %></td>
        <td>
					<%= link_to raw("<i class='icon-file'></i> Details"), store_path(store), :class => 'btn btn-mini' %>
          <%= link_to raw("<i class='icon-plus icon-white'></i> Add Employee"), new_assignment_path, :class => 'btn btn-primary' %>
          <%#= link_to raw("<i class='icon-pencil'></i> Edit"), edit_store_path(store), :class => 'btn btn-mini' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @stores, :previous_label => "Previous&nbsp;", :next_label => "&nbsp;Next" %>

app/views/stores/_assigned_employees.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
			<th class="centered">Pay Level</th>
    </tr>
  </thead>
  <tbody>
    <% @current_assignments.each do |assignment| %>
      <tr>
        <td><%= link_to assignment.employee.name, employee_path(assignment.employee) %></td>
				<td class="centered"><%= assignment.pay_level %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @current_assignments, :previous_label => "Previous&nbsp;", :next_label => "&nbsp;Next" %>


app/views/stores/_current_stores.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Store Name</th>
			<th>Store Phone</th>
      <th class="centered">Staff Count</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%= link_to store.name, store_path(store) %></td>
				<td><%= number_to_phone store.phone %></td>
				<td class="centered"><%= store.assignments.current.size %></td>
        <td>
					<%= link_to raw("<i class='icon-file'></i> Details"), store_path(store), :class => 'btn btn-mini' %>
          <%#= link_to raw("<i class='icon-pencil'></i> Edit"), edit_store_path(store), :class => 'btn btn-mini' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @stores, :previous_label => "Previous&nbsp;", :next_label => "&nbsp;Next" %>

app/views/stores/_form.html.erb
<%= simple_form_for @store, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Store</legend>

		<%= f.input :name %>
		<%= f.input :street %>
		<%= f.input :city %>
		<%= f.input :state, :collection => Store::STATES_LIST %>
		<%= f.input :zip %>
		<%= f.input :phone %>
		<%= f.input :active %>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', stores_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/stores/_guest_stores.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
			<th>Phone Number</th>
    </tr>
  </thead>
  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%= link_to store.name, store_path(store) %></td>
        <td><%= store.street %>, <%= store.city %>, <%= store.state %>, <%= store.zip %></td>
				<td><%= number_to_phone store.phone %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @stores, :previous_label => "Previous&nbsp;", :next_label => "&nbsp;Next" %>

app/views/stores/_inactive_stores.html.erb
<h2>Inactive Stores</h2>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Store Name</th>
			<th>Address</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @inactive_stores.each do |store| %>
      <tr>
        <td><%= link_to store.name, store_path(store) %></td>
				<td><%= store.street %>, <%= store.city %></td>
        <td>
					<%= link_to raw("<i class='icon-file'></i> Details"), store_path(store), :class => 'btn btn-mini' %>
          <%= link_to raw("<i class='icon-pencil'></i> Edit"), edit_store_path(store), :class => 'btn btn-mini' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @inactive_stores, :previous_label => "Previous&nbsp;", :next_label => "&nbsp;Next" %>

app/views/stores/_managers_employees.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Hours Worked</th>
			<th>Last Worked</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% @current_assignments.by_employee.each do |assignment| %>
      <tr>
        <td><%= link_to assignment.employee.name, employee_path(assignment.employee) %></td>
        <td><%= assignment.recent_hours %></td>
        <td><%= assignment.shifts.last.date.strftime("%m/%d/%y") unless assignment.shifts.last.nil? %></td>
        <td><%= link_to raw("<i class='icon-plus icon-white'></i> New Shift"), new_shift_path, :class => 'btn btn-primary', :id => 'Create Shift' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @current_assignments, :previous_label => "Previous&nbsp;", :next_label => "&nbsp;Next" %>


app/views/stores/_store_details.html.erb
<p>
	<h4>
	  Name: <%= @store.name %>
	</h4>
</p>

<p>
  <b>Address:</b><br>
  <%= @store.street %><br />
	<%= @store.city %>, <%= @store.state %> <%= @store.zip %>
</p>

<p>
  <b>Phone:</b><br>
  <%= number_to_phone @store.phone %>
</p>

<p>
  <b>Active:</b> 
  <%= @store.active ? "Yes" : "No" %>
</p>

app/views/stores/_stores_map.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
    <style type="text/css">
      html { height: 100% }
      body { height: 100%; margin: 0; padding: 0 }
      #map_canvas { height: 100% }
    </style>
    <script type="text/javascript"
      src="http://maps.googleapis.com/maps/api/js?key=AIzaSyBHs1x744M8W2JlSMdP9CvSh4PcZDfLgSs&sensor=false">
    </script>
    <script type="text/javascript">
      function initialize() {
        var myOptions = {
          center: new google.maps.LatLng(40.4406, -79.9961),
          zoom: 8,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        };
        var map = new google.maps.Map(document.getElementById("map_canvas"),
            myOptions);
      }
    </script>
  </head>
  <body onload="initialize()">
    <div id="map_canvas" style="width:100%; height:100%"></div>
  </body>
</html>

app/views/stores/edit.html.erb
<%= render :partial => 'form' %>

app/views/stores/index.html.erb
<div class="row">
	<div class="span5">
		<h2>Current Stores</h2>
		<%= render :partial => "current_stores" %>
		<br />
		<%= render :partial => "inactive_stores" unless @inactive_stores.empty? %>
	</div>
	<div class="span7">
		<h2>Find A Store</h2>
		<%= render :partial => "stores_map" %>
	</div>
</div>

<%= link_to raw("<i class='icon-plus icon-white'></i> Add a New Store"), new_store_path, :class => 'btn btn-primary', :id => 'Create Store' %>

app/views/stores/new.html.erb
<%= render :partial => 'form' %>

app/views/stores/show.html.erb
<%= image_tag @store.single_store_map %>

<div class="row">
	<div class="span8">
		<h3><%= @store.name %> Details: </h3>
		<%= render :partial => "store_details" %>
	</div>
	<div class="span4">
		<h3>Current Employees</h3>
		<%= render :partial => "assigned_employees" unless @current_assignments.empty? %>
		<br />
		<%= link_to raw("<i class='icon-plus icon-white'></i> Assign Employee"), new_assignment_path(:id => @store.id, :from => 'store'), :class => 'btn btn-primary' %>
	</div>
</div>


<div class="form-actions">
  <%= link_to raw("<i class='icon-th-list'></i> Display All Stores"), stores_path, :class => 'btn'  %>&nbsp;&nbsp;
  <%= link_to raw("<i class='icon-pencil'></i> Edit #{@store.name}"), edit_store_path(@store), :class => 'btn' %>&nbsp;&nbsp;
  <%= link_to raw("<i class='icon-trash icon-white'></i> Delete #{@store.name}"), store_path(@store), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>