config/routes.rb
Creamery2012::Application.routes.draw do

  # Generated model routes
  resources :stores
  resources :employees
  resources :assignments
  resources :shifts
  resources :jobs
  resources :users
  resources :sessions

  # Authentication routes
  match 'user/edit' => 'users#edit', :as => :edit_current_user
  match 'signup' => 'users#new', :as => :signup
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login
  
  # Semi-static page routes
  match 'home' => 'home#index', :as => :home
  match 'about' => 'home#about', :as => :about
  match 'contact' => 'home#contact', :as => :contact
  match 'privacy' => 'home#privacy', :as => :privacy
  match 'search' => 'home#search', :as => :search
  
  # Set the root url
  root :to => 'home#index'
  
end

app/views/partials/_footer.html.erb

<div id="footer">
	<%= link_to 'Home', home_path %>&nbsp;&nbsp;::&nbsp;&nbsp;
  <%= link_to 'About AMC', about_path %>&nbsp;&nbsp;::&nbsp;&nbsp;
	<%= link_to 'Contact Us', contact_path %>&nbsp;&nbsp;::&nbsp;&nbsp;
	<%= link_to 'Privacy Policy', privacy_path %>
	<br /><br />
	<div id="copy">
		Webmaster: <%= mail_to("holyji@gmail.com", "Jiho Kim", :encode => "javascript") %> 
		&nbsp;&nbsp;&copy 2012
		<p class="supertiny">&nbsp;</p>
	</div>
</div>

app/views/partials/_quick_links.html.erb
<!-- <h2>Quick Tasks</h2>
<ul>Switch to:
	<li><%# link_to 'Add a New Shift', new_shift_path %></li>
	<li><%# link_to 'Add a New Assignment', new_assignment_path %></li>
	<li><%# link_to 'Add a New Employee', new_employee_path %></li>
	<li><%# link_to 'Add a New Store', new_store_path %></li>
	<li><%# link_to 'Add a New Job', new_job_path %></li>
</ul> -->