config/routes.rb
Creamery2012::Application.routes.draw do

  # Generated model routes
  resources :stores
  resources :employees
  resources :assignments
  resources :shifts
  resources :jobs
  resources :users
  resources :sessions

  # Authentication routes
  match 'user/edit' => 'users#edit', :as => :edit_current_user
  match 'signup' => 'users#new', :as => :signup
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login
  
  # Semi-static page routes
  match 'home' => 'home#index', :as => :home
  match 'about' => 'home#about', :as => :about
  match 'contact' => 'home#contact', :as => :contact
  match 'privacy' => 'home#privacy', :as => :privacy
  match 'search' => 'home#search', :as => :search
  
  # Set the root url
  root :to => 'home#index'
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Amazing &amp; Marvelous Creamery</title>
  <%= stylesheet_link_tag "application", "bootstrap.min", "bootstrap-responsive.min" %>
  <%= javascript_include_tag "jquery", "jquery-ui", "jquery_ujs", "bootstrap.min" %>
  <% stylesheet_link_tag    "application", :media => "all" %>
  <% javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<!-- TITLE BAR -->
	<div id="login">
		<p class="ident pull-right">
	    	<% if logged_in? %>
	    		Welcome, <%= link_to current_user.employee.proper_name, employee_path(current_user.employee) %> | 
	    		<%= link_to "Logout", logout_path %>
	      	<% else %>
    	    	<%= link_to 'Login', login_path %>
      		<% end %>
      	</p>
	</div>
	<%= link_to(image_tag('amc_titlebar_1.png'), home_path) %>

	<!-- NAV BAR -->
	<div class="navbar">
	  <div class="navbar-inner">
	    <div class="container">
	      <a class="btn btn-navbar" data-toggle="collapse" data-target=".collapse">
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </a>
				<%# link_to "Home", home_path, :class => "brand" %>
	      <!-- <a class="brand" href="#">Creamery</a> -->
	      <div class="nav-collapse">
	        <ul class="nav">
	        <% if can? :index, Store %>
	          <li><%= link_to "Stores", stores_path %></li>
	        <% end %>
	        <% if can? :create, Employee %>
	          <li><%= link_to "Employees", employees_path %></li>
	        <% end %>
	        <% if can? :index, Assignment %>  
	          <li><%= link_to "Assignments", assignments_path %></li>
	        <% end %>
	        <% if can? :index, Shift %>
	          <li><%= link_to "Shifts", shifts_path %></li>
	        <% end %>
	        <% if can? :index, Job %>  
	          <li><%= link_to "Jobs", jobs_path %></li>
	        <% end %>
	        </ul>



			

	      </div>
	    </div>
	  </div>
	</div>
	
	<!-- MAIN CONTENT -->
	<div class="container">
		<!-- flash messages -->
		<% flash.each do |name, msg| %>
			<div class="alert alert-<%= name == :notice ? "success" : "error" %>">
				<a class="close" data-dismiss="alert">&times;</a>
				<%= msg %>
			</div>
    	<% end %>
		<div class="row">
			<!-- main content placed here -->
			<div class="span12">
				<%= yield %>
			</div>
		</div>
	</div>
	
	<!-- FOOTER -->
	<footer id="footer">
    <div class="container">
			<%= render :partial => "partials/footer" %>
    </div>
  </footer>
</body>
</html>